version: '3.8'

services:
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8000:8000"
    networks:
      - external_network
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    networks:
      - external_network
    volumes:
      - ./infra/data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - external_network
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./infra/data/rabbitmq:/var/lib/rabbitmq
      - ./infra/config/rabbitmq/definitions:/etc/rabbitmq/definitions
    entrypoint: [ "bash", "-c", "rabbitmq-server -detached; sleep 10; rabbitmqctl import_definitions /etc/rabbitmq/definitions/definitions.json; rabbitmqctl stop; rabbitmq-server" ]

volumes:
  mysql-data:

networks:
  external_network:
    external: true
